# Generated by Django 5.0.1 on 2024-01-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_descuento_producto_fecha_fin_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.FloatField(default=0.0, verbose_name='Porcentaje de descuento'),
        ),
    ]
