# Generated by Django 5.0.1 on 2024-01-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
