# Generated by Django 5.0.1 on 2024-01-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_alter_ventadetalle_descuento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventadetalle',
            name='descuento',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='ventadetalle',
            name='total',
        ),
    ]
