# Generated by Django 5.0.1 on 2024-01-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0010_alter_ventadetalle_subtotal_alter_ventadetalle_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='subtotal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
