# Generated by Django 5.0.1 on 2024-01-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0012_alter_ventadetalle_descuento_alter_ventadetalle_iva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='cantidad',
            field=models.FloatField(),
        ),
    ]
