# Generated by Django 5.0.1 on 2024-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0013_alter_ventadetalle_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='iva',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto',
            field=models.FloatField(),
        ),
    ]
