# Generated by Django 5.0.1 on 2024-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0015_venta_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_iva',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
