# Generated by Django 5.0.1 on 2024-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Cajero', 'Cajero'), ('Supervisor', 'Supervisor'), ('Almacenista', 'Almacenista')], max_length=20, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
