# Generated by Django 5.0.1 on 2024-01-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('eslogan', models.CharField(blank=True, max_length=200, null=True, verbose_name='Eslogan')),
                ('calle', models.CharField(max_length=200, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, verbose_name='Numero')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pais')),
                ('cp', models.CharField(blank=True, max_length=5, null=True, verbose_name='Codigo Postal')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('web', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pagina web')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email')),
                ('logo_principal', models.ImageField(blank=True, default='./media/logo.png', null=True, upload_to='logos/')),
                ('logo_secundario', models.ImageField(blank=True, default='./media/logo.png', null=True, upload_to='logos/')),
                ('favicon', models.ImageField(blank=True, default='./media/logo.png', null=True, upload_to='logos/')),
            ],
            options={
                'verbose_name_plural': 'Empresa',
            },
        ),
    ]
