# Generated by Django 5.0.1 on 2024-01-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nombre_corto',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
