# Generated by Django 5.0.1 on 2024-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_nombre_corto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='favicon',
        ),
    ]
